npm install lodash --save
npm install request --save
npm install async --save
npm install chalk --save
npm install express --save
npm install bluebird --save
npm install commander --save
npm install debug --save
npm install react --save
npm install underscore --save
npm install moment --save
npm install mkdirp --save
npm install react-dom --save
npm install fs-extra --save
npm install colors --save
npm install babel-runtime --save
npm install glob --save
npm install body-parser --save
npm install through2 --save
npm install minimist --save
npm install q --save
npm install jquery --save
npm install yeoman-generator --save
npm install prop-types --save
npm install classnames --save
npm install yargs --save
npm install uuid --save
npm install gulp-util --save
npm install babel-core --save
npm install cheerio --save
npm install webpack --save
npm install rxjs --save
npm install winston --save
npm install gulp --save
npm install coffee-script --save
npm install babel-preset-es2015 --save
